### ISSUE TITLE
Love it thanks

### ISSUE THREAD

**Issue by Flukethoughts** [Shaydera/DiabloDungeonTimer#5]
Few questions is this doing anything that blizzard might get a hard on for later on and ban?

Second is there anyway to have it output stats in a widget like format for streams?

**Comment by Shaydera** [comment]
Thank you for the positive feedback!


> Few questions is this doing anything that blizzard might get a hard on for later on and ban?

As we are only parsing a log file, which is created by the game on purpose, and displaying certain information from it in a more useful format, this is not breaking the ToS at all. 
We aren't doing any inputs/automating based on that information and also not interacting with the game files in any other shape or form.

> Second is there anyway to have it output stats in a widget like format for streams?

Currently this is not possible, but I like the idea!
I'll plan to add this feature soon™
